openapi: 3.0.3
info:
  title: Your Project API
  version: 1.0.0
  description: Your project description
paths:
  /api/delete/{id}:
    delete:
      operationId: api_delete_destroy
      description: Delete one image.
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/images/:
    get:
      operationId: api_images_list
      description: Get all saved images.
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ImageModel'
          description: ''
  /api/upload/:
    post:
      operationId: api_upload_create
      description: Upload one image.
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImageModel'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ImageModel'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ImageModel'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImageModel'
          description: ''
components:
  schemas:
    ImageModel:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        title:
          type: string
          maxLength: 64
        file:
          type: string
          format: uri
          pattern: (?:png|jpg|webp)$
        created:
          type: string
          format: date-time
          readOnly: true
      required:
      - created
      - file
      - id
      - title
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
